[tool.poetry]
name = "scrix"
version = "0.1.0"
description = "Weekly BOGO Publix deals"
authors = ["Gavin Roberts <gavinsroberts13@gmail.com>"]
readme = "README.md"
packages = [{ include = "scrix" }]

[tool.poetry.scripts]
scrix = "scrix.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
playwright = "^1.57.0"
google-generativeai = "^0.8.6"
google = "^3.0.0"
google-genai = "^1.56.0"
openai = "^2.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
